<div style="background-color: #4CAF50; color: white; padding: 10px; border-radius: 5px; display: flex; align-items: center;">
    <h1 style="margin: 0 auto; font-size: 30px; font-weight: bold; font-family: Helvetica">การวิเคราะห์ข้อมูลด้วยโครงข่ายประสาทเทียม (Neural Network)</h1>
</div>

<h1 style="font-size: 25px; font-weight: bold; font-family: Helvetica">โครงข่ายประสาทเทียม (Neural Network) คืออะไร</h1>

Neural Networks (โครงข่ายประสาทเทียม) คือโมเดลการคำนวณที่ได้รับแรงบันดาลใจจากการทำงานของสมองมนุษย์ 

โครงข่ายประสาทเทียมประกอบด้วยหน่วยคำนวณเล็กๆ ที่เรียกว่า นิวรอน (Neuron) ซึ่งคล้ายกับเซลล์ประสาทในสมอง นิวรอนเหล่านี้ถูกจัดเรียงเป็นชั้นๆ โดยทั่วไปจะแบ่งออกเป็น 3 ส่วนหลัก ได้แก่

- Input Layer: เป็นชั้นที่รับข้อมูลเข้าไปในระบบ

- Hidden Layer(s): เป็นชั้นที่อยู่ระหว่างชั้นข้อมูลเข้าและชั้นผลลัพธ์ เป็นส่วนที่คำนวณและประมวลผลข้อมูล ซึ่งอาจมีหลายชั้นเรียกว่าระบบ Deep Learning ถ้ามีหลายชั้น

- Output Layer: เป็นชั้นที่ให้ผลลัพธ์ออกมาจากระบบ

<div style="text-align: center;">
    <img src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*SCz0aTETjTYC864Bqjt6Og.png" alt="Regression" width="1200" height="600"/>
    <br>
    <span style="font-size: small;">แผนภาพ Neural Network เบื้องต้น</span>
</div>

<h1 style="font-size: 25px; font-weight: bold; font-family: Helvetica">เครื่องมือที่จะใช้ใน Lab นี้:</h1>

In [1]:
# นำเข้าไลบรารี numpy โดยตั้งชื่อว่า np
import numpy as np

<h1 style="font-size: 25px; font-weight: bold; font-family: Helvetica">โจทย์ปัญหา:</h1>

สมมติว่าเราต้องการโมเดลที่สามารถทำนาย Y โดยมีข้อมูลฟีเจอร์ X ที่กำหนดให้ 3 ข้อมูล ดังนี้:

<div align="center">
    <table>
        <tr>
            <th>X1</th>
            <th>X2</th>
            <th>X3</th>
            <th>Y</th>
        </tr>
        <tr>
            <td>2.5</td>
            <td>1.3</td>
            <td>3.8</td>
            <td>0</td>
        </tr>
        <tr>
            <td>1.7</td>
            <td>2.8</td>
            <td>4.5</td>
            <td>1</td>
        </tr>
        <tr>
            <td>3.1</td>
            <td>1.0</td>
            <td>4.1</td>
            <td>0</td>
        </tr>
        <tr>
            <td>2.0</td>
            <td>3.2</td>
            <td>5.2</td>
            <td>1</td>
        </tr>
        <tr>
            <td>1.6</td>
            <td>2.0</td>
            <td>3.6</td>
            <td>0</td>
        </tr>
        <tr>
            <td>3.3</td>
            <td>1.5</td>
            <td>4.8</td>
            <td>1</td>
        </tr>
        <tr>
            <td>2.8</td>
            <td>2.4</td>
            <td>5.2</td>
            <td>0</td>
        </tr>
        <tr>
            <td>1.2</td>
            <td>2.5</td>
            <td>3.7</td>
            <td>1</td>
        </tr>
        <tr>
            <td>3.0</td>
            <td>1.9</td>
            <td>4.9</td>
            <td>0</td>
        </tr>
        <tr>
            <td>2.3</td>
            <td>3.0</td>
            <td>5.3</td>
            <td>1</td>
        </tr>
    </table>
</div>


<h1 style="font-size: 25px; font-weight: bold; font-family: Helvetica">1. นิวรอน (Neuron)</h1>

นิวรอน (Neuron) ในบริบทของโครงข่ายประสาทเทียม (Neural Networks) คือหน่วยคำนวณพื้นฐานที่ใช้ในการประมวลผลข้อมูลและสร้างผลลัพธ์

โดยนิวรอนจะรับข้อมูลจากนิวรอนอื่นๆ (หรือจากข้อมูลนำเข้าในชั้นแรก) คำนวณผลลัพธ์จากข้อมูลเหล่านั้น และส่งต่อผลลัพธ์ไปยังนิวรอนอื่นๆ ในชั้นถัดไป โดยนิวรอนจะมีองค์ประกอบหลักๆดังนี้:

- **น้ำหนัก (Weights):** เป็นค่าที่แสดงถึงความสำคัญของข้อมูลที่นิวรอนรับเข้ามา นิวรอนจะปรับค่าน้ำหนักเหล่านี้ระหว่างการฝึก (Training) เพื่อเพิ่มความแม่นยำของโมเดล 

     สูตรการคำนวณผลรวมของนิวรอน หรือ $z$ :
      
     <div style="font-size: 30px;">

     $$
     z = \sum_{i=1}^{n} (w_i \times x_i) + b
     $$

     </div>
     
     โดยที่:
     
     - $ w_i $ คือค่าน้ำหนัก

     - $ x_i $ คือค่าข้อมูลนำเข้า
     
     - $ b $ คือค่า bias

- **ฟังก์ชันการกระตุ้น (Activation Function):** ทำหน้าที่เปลี่ยนแปลงค่าที่ได้จากการรวมค่า $z$ ให้กลายเป็นค่าที่จะถูกส่งออกไปยังชั้นถัดไป เช่น

     - **ReLU**: 

     <div style="font-size: 24px;">

     $$ \text{ReLU}(z) = \max(0, z) $$

     </div>

     - **Sigmoid**: 
     
     <div style="font-size: 24px;">

     $$ \text{Sigmoid}(z) = \frac{1}{1 + e^{-z}} $$

     </div>

     - **Softmax**: 

     <div style="font-size: 24px;">

     $$ \text{Softmax}(z_i) = \frac{e^{z_i}}{\sum_{j=1}^{n} e^{z_j}} $$

     </div>
     
- **เอาต์พุต (Output):** คือผลลัพธ์ที่ได้หลังจากผ่านฟังก์ชันการกระตุ้น (Activation Function) และจะถูกส่งไปยังนิวรอนในชั้นถัดไปหรือใช้เป็นผลลัพธ์สุดท้ายของเครือข่าย

<div style="text-align: center;">
    <img src="https://miro.medium.com/v2/resize:fit:640/1*sPg-0hha7o3iNPjY4n-vow.jpeg" alt="Regression" width="700" height="420"/>
    <br>
    <span style="font-size: small;">แผนภาพ Neuron    เบื้องต้น</span>
</div>

<h1 style="font-size: 25px; font-weight: bold; font-family: Helvetica">2. การคำนวณไปข้างหน้า (Forward Propagation)</h1>

การคำนวณไปข้างหน้า (Forward Propagation) ซึ่งหมายถึงกระบวนการที่ข้อมูล (inputs) ถูกส่งผ่านไปตามชั้นของโมเดล (เช่น neuron หรือ layer ต่างๆ) เพื่อคำนวณผลลัพธ์ (output)

โดยทั่วไปแล้ว การส่งผ่านข้อมูลไปข้างหน้าจะเริ่มจากการนำค่า input คูณกับค่าถ่วงน้ำหนัก (weights) ของ neuron และบวกกับค่า bias 

จากนั้นจะนำค่าเหล่านี้ไปผ่านฟังก์ชันการกระตุ้น (activation function) เพื่อสร้าง output สำหรับชั้นนั้นๆ

In [2]:
# ข้อมูล Features จากตาราง
X = np.array([
    [2.5, 1.3, 3.8],
    [1.7, 2.8, 4.5],
    [3.1, 1.0, 4.1],
    [2.0, 3.2, 5.2],
    [1.6, 2.0, 3.6],
    [3.3, 1.5, 4.8],
    [2.8, 2.4, 5.2],
    [1.2, 2.5, 3.7],
    [3.0, 1.9, 4.9],
    [2.3, 3.0, 5.3]
])

# ผลลัพธ์ที่แท้จริง (Labels)
y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

# แยกข้อมูลเป็นอาร์เรย์ของ x1, x2, x3
x1 = X[:, 0]
x2 = X[:, 1]
x3 = X[:, 2]

# ฟังก์ชันการกระตุ้นแบบ Sigmoid
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# ฟังก์ชันการกระตุ้นแบบ ReLU
def relu(z):
    return np.maximum(0, z)

# ฟังก์ชันการกระตุ้นแบบ Softmax
def softmax(z):
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

<h1 style="font-size: 18px;">2.1 การทำ Forward Propagation แบบไม่มี Hidden Layer</h1>

In [3]:
# การทำ Forward Propagation แบบมี Neuron เพียง 1 โหนด

# ค่าถ่วงน้ำหนัก (Weights)
w1 = 0.5; w2 = -0.6; w3 = 0.2

# ค่า bias
b = -0.1

# การคำนวณ z
z = w1 * x1 + w2 * x2 + w3 * x3 + b

# การคำนวณผลลัพธ์โดยใช้ฟังก์ชันการกระตุ้น
a_relu = relu(z)
a_sigmoid = sigmoid(z)

print("ค่า z:", z)
print()
print("ค่า a (Output หลังจาก ReLU):", a_relu)
print()
print("ค่า a (Output หลังจาก Sigmoid):", a_sigmoid)

ค่า z: [ 1.13 -0.03  1.67  0.02  0.22  1.61  0.9  -0.26  1.24  0.31]

ค่า a (Output หลังจาก ReLU): [1.13 0.   1.67 0.02 0.22 1.61 0.9  0.   1.24 0.31]

ค่า a (Output หลังจาก Sigmoid): [0.7558389  0.49250056 0.84157582 0.50499983 0.55477924 0.83341139
 0.7109495  0.43536371 0.77556401 0.57688526]


In [4]:
# การทำ Forward Propagation แบบมี Neuron 2 โหนด

# ค่าถ่วงน้ำหนัก (Weights) และ bias สำหรับ 2 โหนด
weights = np.array([
    [0.5, -0.6, 0.2],  # โหนดที่ 1
    [-0.3, 0.8, 0.1],  # โหนดที่ 2
])

biases = np.array([-0.1, 0.2])

# การคำนวณ z สำหรับแต่ละโหนด
z = np.dot(X, weights.T) + biases

# การคำนวณผลลัพธ์โดยใช้ฟังก์ชันการกระตุ้น
a_softmax = softmax(z)
a_relu = relu(z)

print("ค่า z สำหรับโหนดทั้ง 3:", z)
print()
print("ค่า a (Output หลังจาก ReLU):", a_relu)
print()
print("ค่า a (Output หลังจาก Softmax):", a_softmax)

ค่า z สำหรับโหนดทั้ง 3: [[ 1.13  0.87]
 [-0.03  2.38]
 [ 1.67  0.48]
 [ 0.02  2.68]
 [ 0.22  1.68]
 [ 1.61  0.89]
 [ 0.9   1.8 ]
 [-0.26  2.21]
 [ 1.24  1.31]
 [ 0.31  2.44]]

ค่า a (Output หลังจาก ReLU): [[1.13 0.87]
 [0.   2.38]
 [1.67 0.48]
 [0.02 2.68]
 [0.22 1.68]
 [1.61 0.89]
 [0.9  1.8 ]
 [0.   2.21]
 [1.24 1.31]
 [0.31 2.44]]

ค่า a (Output หลังจาก Softmax): [[0.56463629 0.43536371]
 [0.08241332 0.91758668]
 [0.76674106 0.23325894]
 [0.06537533 0.93462467]
 [0.18846733 0.81153267]
 [0.67260702 0.32739298]
 [0.2890505  0.7109495 ]
 [0.07798824 0.92201176]
 [0.48250714 0.51749286]
 [0.10621499 0.89378501]]


**QUIZ:** จงสร้าง Neural Network ที่ Output layer มีทั้งหมด 3 โหนด จากนั้นทำ Forward Propagation กับข้อมูลตารางข้างต้น และทุกโหนดใช้ฟังก์ชันการกระตุ้นเป็น Softmax

In [16]:
#โค้ดคำตอบที่นี่
# การทำ Forward Propagation แบบมี Neuron 3 โหนด

# ค่าถ่วงน้ำหนัก (Weights) และ bias สำหรับ 3 โหนด
weights = np.array([
    [0.5, -0.3, 0.0],  # โหนดที่ 1
    [-0.6, 0.8, 0.2],  # โหนดที่ 2
    [0.2, 0.1, 2.5],  # โหนดที่ 3
])

biases = np.array([-0.1, 0.2, 0.1])

# การคำนวณ z สำหรับแต่ละโหนด
z = np.dot(X, weights.T) + biases

# การคำนวณผลลัพธ์โดยใช้ฟังก์ชันการกระตุ้น
a_relu = relu(z)
a_softmax = softmax(z)
a_sigmoid = sigmoid(z)

print("ค่า z สำหรับโหนดทั้ง 3:", z)
print()
print("ค่า a (Output หลังจาก ReLU):", a_relu)
print()
print("ค่า a (Output หลังจาก Softmax):", np.round(a_softmax))
print()
print("ค่า a (Output หลังจาก Sigmoid):", a_sigmoid)

ค่า z สำหรับโหนดทั้ง 3: [[ 0.76  0.5  10.23]
 [-0.09  2.32 11.97]
 [ 1.15 -0.04 11.07]
 [-0.06  2.6  13.82]
 [ 0.1   1.56  9.62]
 [ 1.1   0.38 12.91]
 [ 0.58  1.48 13.9 ]
 [-0.25  2.22  9.84]
 [ 0.83  0.9  13.14]
 [ 0.15  2.28 14.11]]

ค่า a (Output หลังจาก ReLU): [[ 0.76  0.5  10.23]
 [ 0.    2.32 11.97]
 [ 1.15  0.   11.07]
 [ 0.    2.6  13.82]
 [ 0.1   1.56  9.62]
 [ 1.1   0.38 12.91]
 [ 0.58  1.48 13.9 ]
 [ 0.    2.22  9.84]
 [ 0.83  0.9  13.14]
 [ 0.15  2.28 14.11]]

ค่า a (Output หลังจาก Softmax): [[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]

ค่า a (Output หลังจาก Sigmoid): [[0.68135373 0.62245933 0.99996393]
 [0.47751518 0.91051994 0.99999367]
 [0.75951092 0.49000133 0.99998443]
 [0.4850045  0.93086158 0.999999  ]
 [0.52497919 0.82635335 0.99993362]
 [0.75026011 0.5938731  0.99999753]
 [0.64106741 0.81457258 0.99999908]
 [0.4378235  0.9020312  0.99994673]
 [0.69635493 0.7109495  0.99999803]
 [0.53742985 

<h1 style="font-size: 18px;">2.2 การทำ Forward Propagation แบบมี Hidden Layer</h1>

In [28]:
# การทำ Forward Propagation แบบมี Hidden layer 1 ชั้น ซึ่งมี Neuron 2 โหนด และ Output layer มี Neuron 1 โหนด 

# ค่าถ่วงน้ำหนัก (Weights) และ bias สำหรับ Hidden Layer (2 โหนด)
weights_hidden_1 = np.array([
    [0.5, -0.6, 0.2],  # โหนดที่ 1
    [-0.3, 0.8, 0.1]   # โหนดที่ 2
])

biases_hidden_1 = np.array([-0.1, 0.2])

# ค่าถ่วงน้ำหนักและ bias สำหรับ Output Layer (1 โหนด)
weights_output = np.array([0.4, -0.7])
bias_output = -0.3

# การคำนวณ z สำหรับ Hidden Layer (2 โหนด)
z_hidden_1 = np.dot(X, weights_hidden_1.T) + biases_hidden_1

# การคำนวณผลลัพธ์ของ Hidden Layer โดยใช้ฟังก์ชันการกระตุ้น (ReLU)
a_hidden_1 = relu(z_hidden_1)

# การคำนวณ z สำหรับ Output Layer (1 โหนด)
z_output = np.dot(a_hidden_1, weights_output.T) + bias_output

# การคำนวณผลลัพธ์ของ Output Layer โดยใช้ฟังก์ชันการกระตุ้น (Sigmoid)
a_output = sigmoid(z_output)

print("ค่า z สำหรับ Hidden Layer (2 โหนด):", z_hidden_1)
print()
print("ค่า a (Output หลังจาก ReLU สำหรับ Hidden Layer):", a_hidden_1)
print()
print("ค่า z สำหรับ Output Layer (1 โหนด):", z_output)
print()
print("ค่า a (Output หลังจาก Sigmoid สำหรับ Output Layer):", a_output)

ค่า z สำหรับ Hidden Layer (2 โหนด): [[ 1.13  0.87]
 [-0.03  2.38]
 [ 1.67  0.48]
 [ 0.02  2.68]
 [ 0.22  1.68]
 [ 1.61  0.89]
 [ 0.9   1.8 ]
 [-0.26  2.21]
 [ 1.24  1.31]
 [ 0.31  2.44]]

ค่า a (Output หลังจาก ReLU สำหรับ Hidden Layer): [[1.13 0.87]
 [0.   2.38]
 [1.67 0.48]
 [0.02 2.68]
 [0.22 1.68]
 [1.61 0.89]
 [0.9  1.8 ]
 [0.   2.21]
 [1.24 1.31]
 [0.31 2.44]]

ค่า z สำหรับ Output Layer (1 โหนด): [-0.457 -1.966  0.032 -2.168 -1.388 -0.279 -1.2   -1.847 -0.721 -1.884]

ค่า a (Output หลังจาก Sigmoid สำหรับ Output Layer): [0.38769775 0.12281918 0.50799932 0.10266113 0.19972724 0.43069896
 0.23147522 0.13622552 0.32717281 0.1319301 ]


**QUIZ:** จงสร้าง Neural Network ที่มี hidden layer 1 ชั้น ซึ่งมีทั้งหมด 3 โหนด และ Output layer มีทั้งหมด 2 โหนด จากนั้นทำ Forward Propagation กับข้อมูลตารางข้างต้น

โดยทุกโหนดใน Hidden layer จะผ่าน Relu และทุกโหนดใน Output layer จะผ่าน Softmax

In [26]:
#โค้ดคำตอบที่นี่
# การทำ Forward Propagation แบบมี Hidden layer 1 ชั้น ซึ่งมี Neuron 3 โหนด และ Output layer มี Neuron 2 โหนด 

# ค่าถ่วงน้ำหนัก (Weights) และ bias สำหรับ Hidden Layer (3 โหนด)
weights_hidden_1 = np.array([
    [0.5, -0.6, 0.2],  # โหนดที่ 1
    [-0.3, 0.8, 0.1],   # โหนดที่ 2
    [0.1, 0.2, -0.3]   # โหนดที่ 3
])

biases_hidden_1 = np.array([-0.1, 0.2, -0.3])

# ค่าถ่วงน้ำหนักและ bias สำหรับ Output Layer (2 โหนด)
weights_output = np.array([
    [0.4, -0.7, 0.2],
    [-0.3, 0.6, -0.4]
])
bias_output = np.array([-0.1, 0.2])

# การคำนวณ z สำหรับ Hidden Layer (3 โหนด)
z_hidden_1 = np.dot(X, weights_hidden_1.T) + biases_hidden_1

# การคำนวณผลลัพธ์ของ Hidden Layer โดยใช้ฟังก์ชันการกระตุ้น (ReLU)
a_hidden_1 = relu(z_hidden_1)

# การคำนวณ z สำหรับ Output Layer (2 โหนด)
z_output = np.dot(a_hidden_1, weights_output.T) + bias_output

# การคำนวณผลลัพธ์ของ Output Layer โดยใช้ฟังก์ชันการกระตุ้น (Sigmoid)
a_output = softmax(z_output)

print("ค่า z สำหรับ Hidden Layer (3 โหนด):", z_hidden_1)
print()
print("ค่า a (Output หลังจาก ReLU สำหรับ Hidden Layer):", a_hidden_1)
print()
print("ค่า z สำหรับ Output Layer (2 โหนด):", z_output)
print()
print("ค่า a (Output หลังจาก Softmax สำหรับ Output Layer):", a_output)

ค่า z สำหรับ Hidden Layer (3 โหนด): [[ 1.13  0.87 -0.93]
 [-0.03  2.38 -0.92]
 [ 1.67  0.48 -1.02]
 [ 0.02  2.68 -1.02]
 [ 0.22  1.68 -0.82]
 [ 1.61  0.89 -1.11]
 [ 0.9   1.8  -1.1 ]
 [-0.26  2.21 -0.79]
 [ 1.24  1.31 -1.09]
 [ 0.31  2.44 -1.06]]

ค่า a (Output หลังจาก ReLU สำหรับ Hidden Layer): [[1.13 0.87 0.  ]
 [0.   2.38 0.  ]
 [1.67 0.48 0.  ]
 [0.02 2.68 0.  ]
 [0.22 1.68 0.  ]
 [1.61 0.89 0.  ]
 [0.9  1.8  0.  ]
 [0.   2.21 0.  ]
 [1.24 1.31 0.  ]
 [0.31 2.44 0.  ]]

ค่า z สำหรับ Output Layer (2 โหนด): [[-0.257  0.383]
 [-1.766  1.628]
 [ 0.232 -0.013]
 [-1.968  1.802]
 [-1.188  1.142]
 [-0.079  0.251]
 [-1.     1.01 ]
 [-1.647  1.526]
 [-0.521  0.614]
 [-1.684  1.571]]

ค่า a (Output หลังจาก Softmax สำหรับ Output Layer): [[0.34524654 0.65475346]
 [0.03248351 0.96751649]
 [0.56094545 0.43905455]
 [0.02253264 0.97746736]
 [0.08866866 0.91133134]
 [0.41824062 0.58175938]
 [0.11815698 0.88184302]
 [0.04019452 0.95980548]
 [0.24323955 0.75676045]
 [0.03714763 0.96285237]]


<h1 style="font-size: 25px; font-weight: bold; font-family: Helvetica">3. การคำนวณย้อนกลับ (Backward Propagation)</h1>

**การคำนวณย้อนกลับ** หรือ **Backward Propagation** เป็นขั้นตอนสำคัญในกระบวนการฝึกอบรม (training) ของโมเดล neural network โดยเฉพาะในการปรับค่าถ่วงน้ำหนัก (weights) และค่า bias ให้กับโมเดล

โดยขั้นตอนการทำงานของ Backward Propagation มีดังนี้

1. **คำนวณความสูญเสีย (Loss Calculation)**: 
   - คำนวณค่าความสูญเสียจากการเปรียบเทียบค่าผลลัพธ์ที่โมเดลทำนายกับค่าผลลัพธ์จริง (labels)
   
2. **คำนวณ Gradient**:
   - คำนวณค่า gradient ของความสูญเสียตามค่าถ่วงน้ำหนักและ bias ในแต่ละชั้นของโมเดล
  
3. **ปรับปรุงค่าถ่วงน้ำหนักและ bias**:
   - ใช้ค่า gradient ที่คำนวณได้ในการปรับปรุงค่าถ่วงน้ำหนักและ bias เพื่อให้ความสูญเสียลดลงในการทำนายครั้งถัดไป (โดยใช้ Gradient Descent)

4. **การส่งข้อมูลย้อนกลับ**:
   - กระบวนการปรับปรุงนี้เริ่มจากชั้นสุดท้ายของโมเดลย้อนกลับไปยังชั้นแรก นี่จึงเป็นที่มาของคำว่า "Backward Propagation" หรือ "การส่งผ่านข้อมูลย้อนกลับ"

<h1 style="font-size: 18px;">3.1 คำนวณค่า Cost ที่เกิดขึ้น</h1>

<h1 style="font-size: 18px;">ในที่นี้จะใช้ Binary Crossentropy เนื่องจากโจทย์ของเราเป็นการทำ Binary Classification</h1>
<h1 style="font-size: 18px;">Binary Crossentropy สามารถคำนวณได้ดังนี้:</h1>

<div style="font-size: 24px;">

$$ J(w,b) = - \frac{1}{m} \sum_{i=1}^{m} [y_i \log(\hat{y}_i) + (1 - y_i) \log(1 - \hat{y}_i)] $$

</div>

โดยที่:

- $J(w,b)$ คือค่า Cost โดยในที่นี้เราใช้เป็น Binary Crossentropy Loss
- $m$ คือจำนวนข้อมูล
- $y_i$ คือค่าจริง (actual) สำหรับข้อมูลลำดับที่ $i$
- $\hat{y}_i$ คือค่าที่ทำนาย (predict) สำหรับข้อมูลลำดับที่ $i$


In [29]:
# การคำนวณ Binary Cross-Entropy (BCE)
def binary_cross_entropy(y_true, y_pred):
    bce = -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
    return bce

# คำนวณ BCE จาก a_output (ผลลัพธ์ที่ผ่าน Sigmoid)
bce = binary_cross_entropy(y, a_output)

print("ค่า Binary Cross-Entropy (BCE):", bce)

ค่า Binary Cross-Entropy (BCE): 1.1316792642273712


<h1 style="font-size: 18px;">3.2 คำนวณ Gradient สำหรับแต่ละโหนดใน Backward Propagation</h1>

3.2.1 คำนวณ Gradient ของโหนดในชั้น Output

ให้:
- `L` เป็นค่า loss

- `a_output` เป็นผลลัพธ์ที่ได้จากฟังก์ชัน Sigmoid ของโหนดสุดท้าย

- `y` เป็นค่าผลลัพธ์จริง (label)

- `z_output` เป็นค่า z ของโหนดสุดท้าย

Gradient ของ Loss ตามค่า `z_output` คำนวณได้จากสมการ:

$$
\frac{\partial L}{\partial z_{\text{output}}} = a_{\text{output}} - y
$$

In [30]:
# คำนวณ Gradient ของ Loss ตามค่า z_output
dz_output = a_output - y
print(dz_output)

[ 0.38769775 -0.87718082  0.50799932 -0.89733887  0.19972724 -0.56930104
  0.23147522 -0.86377448  0.32717281 -0.8680699 ]


จากนั้นคำนวณ Gradient ของค่าถ่วงน้ำหนัก `weights_output` และ bias `bias_output`:

$$
\frac{\partial L}{\partial w_{\text{output}}} = \frac{\partial L}{\partial z_{\text{output}}} \cdot a_{\text{hidden\_1}}
$$

$$
\frac{\partial L}{\partial b_{\text{output}}} = \frac{\partial L}{\partial z_{\text{output}}}
$$

In [31]:
# คำนวณ Gradient ของ w_output และ b_output
dw_output = np.dot(dz_output.T, a_hidden_1)
db_output = np.sum(dz_output, axis=0)
print(dw_output)
print(db_output)

[ 0.74079617 -7.26433838]
-2.4215927869335787


3.2.2 คำนวณ Gradient ของโหนดในชั้น Hidden Layer

ให้:
- `z_hidden_1` เป็นค่า z ของโหนดในชั้นแรก

Gradient ของ Loss ตามค่า `z_hidden_1` คำนวณได้ดังนี้:

$$
\frac{\partial L}{\partial z_{\text{hidden\_1}}} = \frac{\partial L}{\partial z_{\text{output}}} \cdot w_{\text{output}} \cdot \text{ReLU'}(z_{\text{hidden\_1}})
$$

In [32]:
# คำนวณ ReLU' สำหรับ z_hidden_1
relu_prime = z_hidden_1 > 0

# ตรวจสอบขนาดของ dz_output ให้เป็น (batch_size, 1)
dz_output = dz_output.reshape(-1, 1)

# ตรวจสอบขนาดของ weights_output ให้เป็น (1, 2) เพื่อให้ตรงกับขนาดในการคูณ
weights_output_reshape = weights_output.reshape(1, -1)

# คำนวณ Gradient ของ z_hidden_1
dz_hidden_1 = np.dot(dz_output, weights_output_reshape) * relu_prime

print(dz_hidden_1)

[[ 0.1550791  -0.27138842]
 [-0.          0.61402658]
 [ 0.20319973 -0.35559952]
 [-0.35893555  0.62813721]
 [ 0.07989089 -0.13980907]
 [-0.22772042  0.39851073]
 [ 0.09259009 -0.16203265]
 [-0.          0.60464214]
 [ 0.13086913 -0.22902097]
 [-0.34722796  0.60764893]]


จากนั้นคำนวณ Gradient ของค่าถ่วงน้ำหนัก `weights_hidden_1` และ bias `biases_hidden_1`:

$$
\frac{\partial L}{\partial w_{\text{hidden\_1}}} = \frac{\partial L}{\partial z_{\text{hidden\_1}}} \cdot X
$$

$$
\frac{\partial L}{\partial b_{\text{hidden\_1}}} = \frac{\partial L}{\partial z_{\text{hidden\_1}}}
$$

In [33]:
dw_hidden_1 = np.dot(dz_hidden_1.T, X)
db_hidden_1 = np.sum(dz_hidden_1, axis=0)
print(dw_hidden_1)
print(db_hidden_1)

[[-0.47067083 -1.49640637 -1.96707719]
 [ 2.5930897   5.8495909   8.4426806 ]]
[-0.27225499  1.69511495]


<h1 style="font-size: 18px;">3.3 อัปเดต Weights และ Bias ทั้งหมด </h1>

3.3.1 อัปเดต Weights และ Bias สำหรับ Output Layer

เราจะอัปเดตค่า weights (`weights_output`) และ bias (`bias_output`) ของ Output Layer โดยใช้สมการ:

$$
w_{\text{output,new}} = w_{\text{output,old}} - \alpha \cdot \frac{\partial L}{\partial w_{\text{output}}}
$$

$$
b_{\text{output,new}} = b_{\text{output,old}} - \alpha \cdot \frac{\partial L}{\partial b_{\text{output}}}
$$

In [34]:
# อัตราการเรียนรู้ (Learning Rate)
alpha = 0.01

In [35]:
# อัปเดต Weights และ Bias สำหรับ Output Layer
weights_output_reshape -= alpha * dw_output
bias_output -= alpha * db_output
print(weights_output)
print(bias_output)

[ 0.39259204 -0.62735662]
-0.2757840721306642


3.3.2 อัปเดต Weights และ Bias สำหรับ Hidden Layer

เราจะอัปเดตค่า weights (`weights_hidden_1`) และ bias (`biases_hidden_1`) ของ Hidden Layer โดยใช้สมการ:

$$
w_{\text{hidden,new}} = w_{\text{hidden,old}} - \alpha \cdot \frac{\partial L}{\partial w_{\text{hidden}}}
$$

$$
b_{\text{hidden,new}} = b_{\text{hidden,old}} - \alpha \cdot \frac{\partial L}{\partial b_{\text{hidden}}}
$$

In [36]:
# อัปเดต Weights และ Bias สำหรับ Hidden Layer
weights_hidden_1 -= alpha * dw_hidden_1
biases_hidden_1 -= alpha * db_hidden_1
print(weights_hidden_1)
print(biases_hidden_1)

[[ 0.50470671 -0.58503594  0.21967077]
 [-0.3259309   0.74150409  0.01557319]]
[-0.09727745  0.18304885]


<h1 style="font-size: 18px;">3.4 สร้างฟังก์ชันการเทรนโมเดลแบบสำเร็จรูป </h1>

In [37]:
def relu_derivative(z):
    return z > 0

def train_model(X, y, weights_hidden_1, biases_hidden_1, weights_output, bias_output, lr=0.01, epochs=100):
    for epoch in range(epochs):
        # Forward Propagation
        z_hidden_1 = np.dot(X, weights_hidden_1.T) + biases_hidden_1 
        a_hidden_1 = relu(z_hidden_1)
        z_output = np.dot(a_hidden_1, weights_output) + bias_output
        a_output = sigmoid(z_output)

        # Backward Propagation
        dz_output = a_output - y
        dw_output = np.dot(a_hidden_1.T, dz_output)
        db_output = np.sum(dz_output, axis=0)

        dz_output = dz_output.reshape(-1, 1)
        weights_output_reshape = weights_output.reshape(1, -1)
        dz_hidden_1 = np.dot(dz_output, weights_output_reshape) * relu_derivative(z_hidden_1)
        dw_hidden_1 = np.dot(dz_hidden_1.T, X)
        db_hidden_1 = np.sum(dz_hidden_1, axis=0) 

        # อัปเดต Weights และ Biases
        weights_output_reshape -= lr * dw_output
        bias_output -= lr * db_output

        weights_hidden_1 -= lr * dw_hidden_1
        biases_hidden_1 -= lr * db_hidden_1  

        # แสดงผล loss ระหว่างการเทรน
        loss = -np.mean(y * np.log(a_output) + (1 - y) * np.log(1 - a_output))
        print(f'Epoch {epoch+1}/{epochs}, Loss: {loss}')

    return weights_hidden_1, biases_hidden_1, weights_output, bias_output

In [38]:
weights_hidden_1 = np.array([
    [0.5, -0.6, 0.2],  # โหนด 1
    [-0.3, 0.8, 0.1]   # โหนด 2
])

biases_hidden_1 = np.array([-0.1, 0.2])

weights_output = np.array([0.4, -0.7])

bias_output = -0.3

# เทรนโมเดล neural Network
weights_hidden_1, biases_hidden_1, weights_output, bias_output = train_model(
    X, y, weights_hidden_1, biases_hidden_1, weights_output, bias_output, lr=0.01, epochs=10000)

Epoch 1/10000, Loss: 1.1316792642273712
Epoch 2/10000, Loss: 0.9856105006251822
Epoch 3/10000, Loss: 0.9128843764828878
Epoch 4/10000, Loss: 0.8807333283162949
Epoch 5/10000, Loss: 0.8454817182704236
Epoch 6/10000, Loss: 0.8088964755252585
Epoch 7/10000, Loss: 0.7694881901735615
Epoch 8/10000, Loss: 0.7479157988071162
Epoch 9/10000, Loss: 0.7362369795217708
Epoch 10/10000, Loss: 0.7311138632975428
Epoch 11/10000, Loss: 0.7276677987262077
Epoch 12/10000, Loss: 0.7245739975416693
Epoch 13/10000, Loss: 0.7217861229584979
Epoch 14/10000, Loss: 0.7192678903838011
Epoch 15/10000, Loss: 0.7169897477437547
Epoch 16/10000, Loss: 0.7149267840614774
Epoch 17/10000, Loss: 0.7130573814556798
Epoch 18/10000, Loss: 0.7113623340151244
Epoch 19/10000, Loss: 0.7098242692617573
Epoch 20/10000, Loss: 0.7084272703683258
Epoch 21/10000, Loss: 0.7071566331765655
Epoch 22/10000, Loss: 0.7059987134586272
Epoch 23/10000, Loss: 0.7049408332388654
Epoch 24/10000, Loss: 0.7039712238551745
Epoch 25/10000, Loss: 0.7

In [39]:
# แสดงผลลัพธ์สุดท้าย
print("Weights Hidden Layer 1:")
print(weights_hidden_1)
print("\nBiases Hidden Layer 1:")
print(biases_hidden_1)
print("\nWeights Output Layer:")
print(weights_output)
print("\nBias Output Layer:")
print(bias_output)

Weights Hidden Layer 1:
[[ 0.29848419 -0.91612852 -0.31764433]
 [-0.40923622  0.54015671 -0.26907952]]

Biases Hidden Layer 1:
[4.03081519 0.12311548]

Weights Output Layer:
[-1.99264839 -0.48543783]

Bias Output Layer:
2.5949415636795097
